version: "3"

services:
  api:
    build: .
    command: api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=True
    restart: unless-stopped

  ui:
    build: .
    command: ui
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - HOST=api
      - PORT=8000
    depends_on:
      - api
    restart: unless-stopped
